import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/lib/query-provider";

export const metadata: Metadata = {
  title: "Dughu",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

/**
 * Viewport export Next.js : active viewport-fit=cover pour que les
 * variables CSS env(safe-area-inset-*) soient disponibles sur iOS.
 * Sans cela, la barre système iPhone peut chevaucher la navigation mobile.
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full">
        <QueryProvider>
          {children}
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
